/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EngineInteraction_EngineInteraction */

#ifndef _Included_EngineInteraction_EngineInteraction
#define _Included_EngineInteraction_EngineInteraction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EngineInteraction_EngineInteraction
 * Method:    initGame
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_EngineInteraction_EngineInteraction_initGame
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     EngineInteraction_EngineInteraction
 * Method:    makeMove
 * Signature: (IIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_EngineInteraction_EngineInteraction_makeMove
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     EngineInteraction_EngineInteraction
 * Method:    fetchState
 * Signature: (Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_EngineInteraction_EngineInteraction_fetchState
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     EngineInteraction_EngineInteraction
 * Method:    botMove
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_EngineInteraction_EngineInteraction_botMove
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     EngineInteraction_EngineInteraction
 * Method:    isCheckMate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_EngineInteraction_EngineInteraction_isCheckMate
  (JNIEnv *, jobject);

/*
 * Class:     EngineInteraction_EngineInteraction
 * Method:    isStaleMate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_EngineInteraction_EngineInteraction_isStaleMate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
